### ISSUE TITLE
webhook duplicates

### ISSUE THREAD

**Issue by edwardthomas** [justinhunt/moodle-local_trigger#1]
Hi Justin, 

I'm having an issue with the webhook creating duplicates. I'm trying to send out 2 webhooks (one for each database) when an event is triggered in moodle. Each webhook has a different URL. The issue is that I'll receive multiple copies of the same webhook for each server. In turn this bogs down the server. 

could you please take a look at this?

**Comment by justinhunt** [comment]
Sure. I will look at it shortly and get back to you here ..

**Comment by justinhunt** [comment]
This should fixed now https://github.com/justinhunt/moodle-local_trigger/commit/56b197f4072ba1e72b6dc3c5c8ef3ae3109c9dc0

**Comment by edwardthomas** [comment]
Just wanted to confirm that I tested this update and the issue is resolved. Thanks again.
