### ISSUE TITLE
Issue with Welcome Email Using Zapier and Custom HTML Template

### ISSUE THREAD

**Issue by Jolios** [justinhunt/moodle-local_trigger#5]
Hi Justin,

First, thank you for your excellent work on the local trigger plugin. It's been incredibly helpful for integrating Moodle with Zapier.

I'm encountering an issue with the welcome email when creating users via Zapier. While the custom HTML template displays correctly for manually added users, it doesn't format properly for users added through Zapier.

I found that the "MailFormat" option needs to be set to 1 in API calls for HTML emails to display correctly (https://moodle.org/mod/forum/discuss.php?d=450546#p1810711)

Could you guide me on how to set this option in the plugin?

Thank you!

**Comment by justinhunt** [comment]
The Zapier + local_trigger integration as you discovered does not set the mailformat option when creating users. It just sets the most basic fields. We might add more fields, or find some clever way to pass in specific fields we were interested in.

But I looked at the API and it should use the site default preference for unspecified properties. So if mailformat is not passed in it should use the value of $CFG->defaultpreference_mailformat. This can be set at:
_Site administration->Users->Accounts->User default preferences_

Can you check that?

**Comment by Jolios** [comment]
I checked the site default preference, and the email format is set to "Pretty HTML"
![email-format](https://github.com/user-attachments/assets/b82cbc0b-dc18-4c9c-a58e-c95542d9e998)

Given the current limitations, I opted for an alternative solution by disabling welcome emails in Moodle and sending them through Zapier instead. This workaround fits our needs for now, so I'll close the issue.

**Comment by justinhunt** [comment]
OK I think the default mail format being ignored might be a bug in Moodle's create user process. But creating users via API is so seldom few people ran into it. I am glad you found a workaround
